### ISSUE TITLE
Beatles filenames contain colons

### ISSUE THREAD

**Issue by ethanmad** [eecs183/creative-ai#1]
There are two data files containing colons in their names ([`pantomime:everywhere_it's_christmas`](https://github.com/eecs183/creative-ai/blob/master/data/lyrics/the_beatles/pantomime:everywhere_it's_christmas.txt) and [`speech:_eric_morecambe_and_ernie_wise.txt`](https://github.com/eecs183/creative-ai/blob/master/data/lyrics/the_beatles/speech:_eric_morecambe_and_ernie_wise.txt)) . Colons are not allowed in file names on Windows, meaning the file names are automatically truncated on Windows systems upon clone, causing a change that Git tracks.

This is especially problematic since most of the students in this course are unfamiliar with Git, which might lead them to stage and commit the file renames (best case scenario they just get annoyed by the changes but don't stage them).

I have no good, global solution for this since students already have their forks, but in the future, if Windows is a supported platform, do not include colons in file names.

**Comment by paralin** [comment]
@tsafavi Why would you close this without even commenting anything? As an outside observer it seems really poorly managed.

**Comment by amirkamil** [comment]
@paralin I don't know what your motivation is for posting a public complaint on a project specification for a course at a university with which you have no affiliation, but it is extremely unprofessional and will not be tolerated..
